logging:
    file:
        name: logs/farmstory.log
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        root: info

mybatis:
    mapper-locations: classpath:mappers/**/*.xml

server:
    port: 8080
    servlet:
        context-path: /farmstory

spring:
    application:
        name: farmstory

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 1234
        url: jdbc:mysql://localhost/farmstory
        username: root

    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false

    # 이메일 설정
    mail:
        host: smtp.gmail.com
        port: 587
        username: qksrm5546@gmail.com
        password: syyi llmm zjkw jchx
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true
        # JPA 설정
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true

    servlet:
        multipart:
            location: uploads/
            max-file-size: 10MB

    thymeleaf:
        prefix: classpath:/templates

    security:
        oauth2:
            client:
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        user-name-attribute: id
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me

                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent



                registration:
                    kakao:
                        client-name: kakao
                        authorization-grant-type: authorization_code

                        # 카카오 > 내 애플리케이션 > 카카오 로그인 > 등록한 Redirect URI 입력
                        #redirect-uri: http://ec2-54-180-15-253.ap-northeast-2.compute.amazonaws.com:8080/farmstory/login/oauth2/code/kakao
                        redirect-uri: http://ec2-3-39-72-175.ap-northeast-2.compute.amazonaws.com:8080/farmstory/login/oauth2/code/kakao
                        #redirect-uri: http://localhost:8080/farmstory/login/oauth2/code/kakao

                        # 카카오 > 내 애플리케이션 > 요약정보 > REST API 키 입력
                        client-id: 3227ae68356a2d41ac3d1a0a451d3676

                        # 카카오 > 내 애플리케이션 > 카카오 로그인 > 보안 > Client Secret 생성 후 입력
                        client-secret: LypzViPdKrOEqoDneoYdF3j84fw9WAlK

                        client-authentication-method: client_secret_post
                        scope: profile_nickname, profile_image, account_email

                    google:
                        client-id: 979608545498-9vr7dn0ce9id17dqlce5b6kvsm8jv882.apps.googleusercontent.com
                        client-secret: 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
                        #redirect-uri: http://localhost:8080/farmstory/login/oauth2/code/google
                        redirect-uri : http://ec2-3-39-72-175.ap-northeast-2.compute.amazonaws.com:8080/farmstory/login/oauth2/code/google
                        #redirect-uri : http://ec2-54-180-15-253.ap-northeast-2.compute.amazonaws.com:8080/farmstory/login/oauth2/code/google

                        scope:
                            - email
                            - profile

# 파일 업로드 설정
file:
    upload:
        path: files/

    # 개발용
    prodImg:
        path: prodImg/

    # 배포용
    #prodImg:
        #path: file:/home/farmstory/prodImg/

